version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - node.store.allow_mmap=false
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200

  embedding:
    image: agix/sentence-transformers:all-mpnet-base-v2_ms-marco-MiniLM-L-4-v2_mmarco-mMiniLMv2-L6-H384-v1
    container_name: embedding
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    runtime: nvidia
    ports:
      - 5000:5000